#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/socializingapp?currentSchema=public
#    username: postgres
#    password: admin
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: validate # the first time you should replace "validate" with "create" so it makes the schema and then leave is a "validate"
#    show-sql: false
#    properties:
#      hibernate:
#        format_sql: true
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#
#application:
#  security:
#    jwt:
#      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
#      expiration: 86400000 # a day
#      refresh-token:
#        expiration: 604800000 # 7 days
#
#server:
#  port: 8080